Reorganize project and add new av-cod-server service with start/stop
getditto/cod-polaris-m1 pull request #31
Opened 2024-02-27 23:14 UTC by ajfabbri

Goal is to implement v0 of client-side (autonomous vehicle, or "AV" side) API for Trial Start and Trial End messages. Being a separate process, intended to run in a container, the API is exposed via HTTP REST.

- Reorganize stuff into subdirectories now that there are three prototypes brewing in this repo.
- Initial implementation of `av-cod-server` with support for start / end APIs.

2024-02-29 02:36 UTC, ajfabbri commented on src/util/cond_promise.ts
> +    }
I don't know if `setImmediate()` is required here. The story is, node has this thing [EventEmitter](https://nodejs.org/en/learn/asynchronous-work/the-nodejs-event-emitter) which is used a lot--including for events that fire from the node `http.Server` class we use. Those `on()` callbacks are called synchronously--so to be cautious I don't call `this.resolveCb()` directly from `resolve()` (which is called via an `on()` event handler). Instead, I tell the node async runtime to call the `resolveCb()` on the next tick of its event loop. This is what happens when you're experienced with async code but a noob at javascript / node. 😅

2024-02-29 02:39 UTC, ajfabbri commented on src/av-cod-server/http_server.ts
> +        this.server.close()
Related to below comment: when you call `http.Server.close()`, it doesn't close immediately. It starts it async, and then fires an `Event` of `'close'`. So, to be able to `await` (block current task) until the server actually shuts down, you have to wait (put current task to sleep) until that `'close'` event is emitted. Thus I created this `CondPromise` thing above.

2024-02-29 14:09 UTC, kitplummer requested changes
In general, I believe the practice is when a `data` block is passed with the HTTP request it needs to be either PUT or POST.  In REST-y circles - that usually also addresses CREATE or UPDATE actions.  But most modern HTTP clients won't require extra headers to handle data if it is a POST (ala cURL).  I know the contact reports are POST'd - as defined in the MAPG ICD - but didn't look to see if anything else is specifically POST or GET.  So think we should do what is the norm here.

2024-02-29 14:09 UTC, kitplummer commented on src/av-cod-server/http_server.ts
> +                if (req.method !== 'GET') {
Pretty sure this should be a POST.

2024-02-29 14:09 UTC, kitplummer commented on src/av-cod-server/http_server.test.ts
> +        http.get(url, (res: IncomingMessage) => {
Commented in impl that I believe this should be a POST.

2024-03-01 01:40 UTC, ajfabbri commented
I am thinking
GET status/start/stop I.e. "give me status please"
PUT contact reports, telemetry I.e. "I'm creating a new contact report, etc."
Telemetry could maybe be POST.. I'm not there yet.

IIUC, you're saying PUT/POST w/ an empty request to query status? 

Aside, for your entertainment: I actually think the semantic binding with http verbs and general purpose APIs is overhyped (a layering violation except for trivial CRUD APIs). Personally I'm cool with "always POST" but people seem not to like it 😅.

2024-03-01 01:42 UTC, ajfabbri commented
Oh I see your update now. Thanks for the review. 😅

2024-03-04 19:01 UTC, merged